# -*- coding: utf-8 -*-
{
    "name": "KA Stock",
     'description': """
Module Stock yang di sesuaikan dengan kebutuhan PT. Kebon Agung.

    """,
    "version": "1.01",
    "author": "PT. Kebon Agung",
    "license": "AGPL-3",
    "category": "Stock",
    "website": "www.ptkebonagung.com",
    "depends": [
				"stock_account", 
                "ka_account", 
                "ka_base", 
                "ka_manufacture",
                "ka_timbang",
                "ka_logistik_master"], 
    "data": [
        "data/ir_sequence.xml",
        "data/product_data.xml",
        "security/ir.model.access.csv",
        "security/stock_security.xml",
        "report/serah_terima_gula_harian.xml",
        "report/tmpl_serah_terima_gula_harian.xml",
        "report/serah_terima_tetes_harian.xml",
        "report/tmpl_serah_terima_tetes_harian.xml",
        "report/laporan_harian_gula.xml",
        "report/tmpl_laporan_harian_gula.xml",
        "report/laporan_harian_ampas.xml",
        "report/tmpl_laporan_harian_ampas.xml",
        "report/laporan_harian_tetes_label.xml",
        "report/templ_laporan_harian_tetes.xml",
        "wizard/stock_backorder_confirmation_view.xml",
        "views/stock_move_daily_sugar_view.xml",
#         "views/stock_move_daily_sugarpremium_view.xml",
        "views/stock_move_daily_sugar_retail_view.xml",
        "views/stock_config_settings.xml",
        "views/product_view.xml",
        "views/stock_move_daily_molasses_view.xml",
        "views/stock_move_daily_bagasse_view.xml",
        "views/stock_tank_view.xml",
        "views/ka_manufacture_daily_view.xml",
        "views/timbang_view.xml",
        "views/stock_view.xml",
        "views/stock_picking_translate_view.xml",
        "views/product_template_translate_view.xml"
        ],
    'installable': True,
}