# -*- coding: utf-8 -*-
{
    "name": "KA Sale",
     'description': """
Module Sales yang di sesuaikan dengan kebutuhan PT. Kebon Agung.
Yang dapat mendukung hutang piutang atas PG:

- Create SO Direksi --> Create SO dan Penerimaan di PG
    """,
    "version": "1.01",
    "author": "PT. Kebon Agung",
    "license": "AGPL-3",
    "category": "Sale",
    "website": "www.ptkebonagung.com",
    "depends": ["sale_order_dates", 
                "stock",
                "sale",
                "ka_base", 
                "ka_account", 
                "ka_logistik_master",
                "ka_timbang"],
    "data": [ 
        "report/tmpl_delivery_order.xml",
        "report/tmpl_delivery_molasses.xml",
        "report/tmpl_bukti_keluar_gula.xml",
        "report/tmpl_bukti_keluar_gula_natura.xml",
        "report/tmpl_report_piutang_retail.xml",
        "report/tmpl_report_stock_monthly.xml",
        "report/tmpl_report_penjualan_gula_retail.xml",
        "report/delivery_slip.xml",
        "report/delivery_slip_molasses.xml",
        "report/bukti_keluar_gula.xml",
        "report/bukti_keluar_gula_natura.xml",
        "report/report_delivery_order.xml",
        "report/report_piutang_retail.xml",
        "report/report_stock_monthly.xml",
        "report/report_penjualan_gula_retail.xml",     
        "report/slip_kwitansi_so.xml",
        "report/tmpl_slip_kwitansi_so.xml",
        "report/report_contract_gula.xml",
        "report/report_contract_tetes.xml",
        "security/ir.model.access.csv",
        "security/sale_security.xml",
        "views/sale_view.xml",
        "views/stock_view.xml",
        "views/sale_contract_view.xml",
        "views/sale_dashboard_view.xml",
        "views/templates.xml",
        "views/account_invoice_view.xml",
        "views/res_partner_view.xml",
        "views/ka_sale_order_category_view.xml",
        "views/sale_order_translate_view.xml",
        "views/account_invoice_translate_view.xml",
        "wizard/stock_picking_split_wizard.xml",
        "wizard/report_piutang_retail_view.xml",
        "wizard/report_stock_monthly_view.xml",
        "wizard/report_penjualan_gula_retail_wizard_view.xml",
        ],
    'css': [
        'static/src/css/ka_sale_order_dashboard.css',
    ],
    'installable': True,
}