# -*- coding: utf-8 -*-
from . import chart_template
from . import account
from . import account_move
from . import attachment
from . import res_users
from . import account_invoice
from . import account_penalty
from . import ka_account_voucher
from . import ka_account_payment
from . import ka_account_payment_confirm
from . import account_bank_statement
from . import account_config_setting
from . import account_journal_dashboard
from . import account_cash_nominal
from . import ka_account_fiscalyear
from . import ka_account_fiscalmonth
from . import res_partner_bank
from . import ka_account_periodic