# -*- coding: utf-8 -*-
{
    "name": "KA Account",
     'description': """
Module Akuntansi yang di sesuaikan dengan kebutuhan PT. Kebon Agung.

- Customize Account Template
    """,
	"version": "1.01",
    "author": "PT. Kebon Agung",
    "license": "AGPL-3",
    "category": "Accounting",
    "website": "www.ptkebonagung.com",
    "depends": [
        "account",
        "account_cancel",
        "web", 
        "document",
        "ka_base", 
        "ka_logistik_master",
        "report_xlsx",
        "ka_hr_pegawai"
    ], 
    "data": [
        "data/account_type_data.xml",
        "data/ir_sequence.xml",
        "data/ir_cron_data.xml",
        "data/ka_account_fiscalmonth_data.xml",
        "security/ir.model.access.csv",
        "security/account_security.xml",
        "report/report_bukti_memorial.xml",
        "report/slip_penerimaan_kas.xml",
        "report/slip_penerimaan_kas_plus.xml",
        "report/tmpl_slip_penerimaan_kas.xml",
        "report/tmpl_slip_penerimaan_kas_plus.xml",
        "report/report_proposed_payment.xml",
        "report/tmpl_proposed_payment.xml",
        "report/ka_account_report_confirmed_payment.xml",
        "report/report_confirmed_payment_view.xml",
        "report/slip_setoran_bank.xml",
        "report/slip_setoran_kas_keluar.xml",
        "report/tmpl_slip_setoran_bank.xml",
        "report/tmpl_slip_setoran_kas_keluar.xml",
        "report/ka_general_ledger_view.xml",
        "report/laporan_buku_besar.xml",
        "report/tmpl_laporan_buku_besar.xml",
        "report/daily_cash_report.xml",
        "report/cash_bank_report.xml",
        "report/daily_cash_report_tmpl.xml",
        "report/report_rekap_vendor_payment.xml",
        "report/report_rekap_vendor_payment_tmpl.xml",
        "report/cash_flow_report_tmpl.xml",
        "report/cash_flow_report.xml",
        "report/ka_trial_balance_report_tmpl.xml",
        "views/templates.xml", 
        "views/chart_template_view.xml", 
        "views/account_view.xml",
        'views/open_chart.xml',
        "views/financial_report.xml",
        "report/report_financial_custom_portrait.xml",
        "report/report_financial_custom_landscape.xml",
        # "views/report_financial.xml",
        # "views/report_balance_sheet_horizontal.xml",
        "views/account_invoice_view.xml",
        "views/account_penalty_view.xml",
        "views/account_bank_statement_view.xml",
        "views/ka_account_voucher_view.xml",
        "views/account_config_setting_view.xml",
        "views/ka_account_payment_view.xml",
        "views/ka_account_payment_confirm_view.xml",
        "views/account_journal_dashboard_view.xml",
        "views/account_cash_nominal_view.xml",
        "views/res_bank_partner_view.xml",
        "views/webclient_templates.xml",
        "views/account_fiscalyear.xml",
        "views/ka_account_periodic_view.xml",
        "wizard/voucher_print_wizard.xml",
        "wizard/bank_statement_line_import_wizard_view.xml",
        "wizard/ka_account_payment_confirm_wizard_view.xml",
        "wizard/ka_account_print_payment_wizard.xml",
        "wizard/ka_account_payment_export_faktur_pajak_wiz.xml",
        "wizard/rekap_vendor_payment_wizard_view.xml",
        "wizard/cash_flow_report_wizard_view.xml",
        "wizard/cash_bank_report.xml",
        "wizard/ka_daily_cash_view.xml",
        "wizard/ka_account_export_dbf_wizard.xml",
        "wizard/trial_balance_report_wizard_view.xml",
        "wizard/financial_report_detail_wizard_view.xml",
        "report_neraca_lama/neraca_saldo_lama_tmpl.xml",
        "report_neraca_lama/neraca_saldo_lama_view.xml",
    ],
    'qweb': ['static/src/xml/*.xml'],
    'installable': True,
}